url: http://localhost:4000
baseurl: 

# Site settings
title: My Portofolio
email: dontmotherthink@gmail.com
description: "We’re small, growing company of just 30 people and are professional for graphic design."


# titles and social links
nama: Dont Motherthink
tagline: Logo/design/freelancer/videomaker

# Social networks usernames
fb: dontmotherthink
twitter: dontmotherthink
dribbble: dontmotherthink
ig: dont.motherthink

# Alamat dan Kontak
telp: 080989999
alamat: Jl. Anggajaya 2 No.11, Condongcatur, Depok, Sleman, Yogyakarta 55281


# Build settings
markdown: kramdown
permalink: pretty