url: http://localhost:4000
baseurl: 

# Site settings
title: My Portofolio
email: dontmotherthink@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# titles and social links
nama: Dont Motherthink
tagline: Logo/design/freelancer/videomaker

# Social networks usernames
fb: dontmotherthink
twitter: dontmotherthink
dribbble: dontmotherthink
ig: dont.motherthink

# Alamat dan Kontak
telp: 080989999
alamat: Jl. Anggajaya 2 No.11, Condongcatur, Depok, Sleman, Yogyakarta 55281


# Build settings
markdown: kramdown
permalink: pretty