url: http://localhost:4000
baseurl: 

# Site settings
title: Awesome Testing
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# titles and social links
nama: Dont Motherthink
tagline: Logo/design/freelancer/videomaker

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
fb: dontmotherthink
twitter: dontmotherthink
dribbble: dontmotherthink
ig: dont.motherthink

# Alamat dan Kontak
telp:
alamat:


# Build settings
markdown: kramdown
permalink: pretty